version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    networks:
      - chat_network

  peer1:
    build:
      context: .
      dockerfile: peerDockerfile
    depends_on:
      - db
    networks:
      - chat_network

  peer2:
    build:
      context: .
      dockerfile: peer2Dockerfile
    depends_on:
      - db
    networks:
      - chat_network

networks:
  chat_network:
